Kong/lua-resty-events

README.md

fix(doc) readme clean

---

.github/workflows/tests.yml
Makefile
lualib/resty/events/broker.lua
lualib/resty/events/callback.lua
lualib/resty/events/codec.lua
lualib/resty/events/compat/callback.lua
lualib/resty/events/compat/init.lua
lualib/resty/events/disable_listening.lua
lualib/resty/events/frame.lua
lualib/resty/events/init.lua
lualib/resty/events/protocol.lua
lualib/resty/events/queue.lua
lualib/resty/events/worker.lua
src/ngx_lua_events_module.c
t/broadcast.t
t/callback-compat.t
t/callback.t
t/codec.t
t/disable-listening.t
t/events-compat.t
t/events.t
t/stream-broadcast.t
t/stream-events.t

change to `publish` `subscribe` and others.

feat(*) rebased new apis

---

README.md

doc(*) add context desc

---

lualib/resty/events/init.lua
lualib/resty/events/worker.lua
t/privileged.t

worker_id is `nil` in privileged worker. This PR let library can work with privileged worker.

fix(init) check privileged worker

---

README.md
lualib/resty/events/broker.lua
lualib/resty/events/init.lua
lualib/resty/events/queue.lua
lualib/resty/events/worker.lua
t/events.t

* max queue length increase to 1024 * 10
* use first/last index to access queue item
See : https://www.lua.org/pil/11.4.html

perf(queue) use index to access queue

---

README.md
lualib/resty/events/init.lua
lualib/resty/events/worker.lua
t/listening-off.t

feat(*): add `testing=true` for resty cli testing

---

.github/workflows/lualint

We have developed a tool called Lualint, which checks for basic formatting errors in user-submitted code, thereby reducing the workload of reviewers.

chore(ci): exprimental lualint integration

---

README.md
lualib/resty/events/frame.lua
lualib/resty/events/worker.lua
t/events.t

fix(lib): check send payload length

---

lualib/resty/events/init.lua
lualib/resty/events/worker.lua

chore(lib): bump to v0.1.5

---

lualib/resty/events/worker.lua

feat(worker): random delay down to 10ms~50ms

---

lualib/resty/events/init.lua
lualib/resty/events/worker.lua

chore(lib): bump to 0.1.6

---

.github/workflows/tests.yml

Waiting for 1.21.4.2 official release.

chore(ci): add openresty 1.21.4.2 to ci matrix

---

.github/workflows/tests.yml

See: https://openresty.org/cn/ann-1025003001.html

chore(ci): add openresty 1.25.3.1 in test matrix

---

lualib/resty/events/broker.lua
lualib/resty/events/protocol.lua

Missing most probably a busted test (testing this with Test::Nginx is difficult)

fix(broker): do not premature kill threads when not exiting

---

lualib/resty/events/worker.lua

This allows the `events_thread` continue to function even when broker connection is lost or broker crashes. It will also make it faster to reconnect broker as the communication timer does not need to wait for events thread.

fix(worker): separate communication and event processing to different timers

---

lualib/resty/events/compat/init.lua

This reverts commit 3511ffbdbfb303b9c7d90f46a34e5532ec5714ac.
I will revert this commit and open a new PR for it

Revert "style(lib/compat): update module version"

---

lualib/resty/events/broker.lua
lualib/resty/events/worker.lua

KAG-5212
Try to simplify the log operation.

style(lib): style clean for logging worker info

---

README.md

docs(readme): production ready now

---

lualib/resty/events/worker.lua

KAG-5319
Related doc: https://docs.google.com/document/d/14Xu8HtHZNF-of49LrLiyETlG_uE6tYa4xdqIPhoD3m0/edit

feat(worker): restart event thread to avoid memory leak

---

.github/workflows/tests.yml

chore(ci): tests with openresty 1.27.1.1
